version: '3.3'

services:
  db:
    image: 'postgres:13'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: prodops
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
